{
 "title": "Primary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(apache_up, instance)"
   },
   {
    "name": "port",
    "query": "label_values(apache_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginxplus_http_requests_total{instance=~\"127.0.0.1:9113\"}[10s]) or rate(nginx_http_requests_total{instance=~\"127.0.0.1:9113\"}[10s])",
     "legendFormat": "balancer"
    },
    {
     "expr": "rate(apache_accesses_total{instance=~\"10.0.0.11:9117\"}[10s])",
     "legendFormat": "alpha"
    },
    {
     "expr": "rate(apache_accesses_total{instance=~\"10.0.0.7:9117\"}[10s])",
     "legendFormat": "beta"
    },
    {
     "expr": "rate(apache_accesses_total{instance=~\"10.0.0.3:9117\"}[10s])",
     "legendFormat": "gamma"
    }
   ]
  },
  {
   "title": "CPU Load (Node Exporter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'10.0.0.11:9100'}[10s])) or sum(irate(node_cpu{mode=\"system\",instance=~'10.0.0.11:9100'}[10s]))",
     "legendFormat": "ALpha"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'10.0.0.7:9100'}[10s])) or sum(irate(node_cpu{mode=\"system\",instance=~'10.0.0.:9100'}[10s]))",
     "legendFormat": "Beta"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'10.0.0.3:9100'}[10s])) or sum(irate(node_cpu{mode=\"system\",instance=~'10.0.0.3:9100'}[10s]))",
     "legendFormat": "Gamma"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'localhost:9100'}[10s])) or sum(irate(node_cpu{mode=\"system\",instance=~'localhost:9100'}[10s]))",
     "legendFormat": "Balancer"
    }
   ]
  },
  {
   "title": "Upstream 4xx answers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginxplus_upstream_server_responses{server=~\"10.0.0.11:80\",code=\"4xx\"}[10s])",
     "legendFormat": "alpha"
    },
    {
     "expr": "irate(nginxplus_upstream_server_responses{server=~\"10.0.0.7:80\",code=\"4xx\"}[10s])",
     "legendFormat": "beta"
    },
    {
     "expr": "irate(nginxplus_upstream_server_responses{server=~\"10.0.0.3:80\",code=\"4xx\"}[10s])",
     "legendFormat": "gamma"
    }
   ]
  },
  {
   "title": "HttpHealth checks failed",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "irate(nginxplus_upstream_server_health_checks_fails{server=~\"10.0.0.11:80\"}[5s])",
     "legendFormat": "alpha"
    },
    {
     "expr": "irate(nginxplus_upstream_server_health_checks_fails{server=~\"10.0.0.7:80\"}[5s])",
     "legendFormat": "beta"
    },
    {
     "expr": "irate(nginxplus_upstream_server_health_checks_fails{server=~\"10.0.0.3:80\"}[5s])",
     "legendFormat": "gamma"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(apache_up{instance=~\"10.0.0.11:9117\"} == 1)",
     "legendFormat": "Alpha Up"
    },
    {
     "expr": "scalar(count(apache_up{instance=~\"10.0.0.11:9117\"} == 0))",
     "legendFormat": "Alpha Down"
    }
   ]
  },
  {
   "title": "Uptime Alpha",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 15 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{instance=~\"10.0.0.11:9117\"}"
    }
   ]
  },
  {
   "title": "Uptime Beta",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 15 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{instance=~\"10.0.0.7:9117\"}"
    }
   ]
  },
  {
   "title": "Uptime Gamma",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 15 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{instance=~\"10.0.0.3:9117\"}"
    }
   ]
  },
  {
   "title": "Uptime Balancer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 15 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"localhost:9100\"} - node_boot_time_seconds{instance=~\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_workers{state=\"busy\",instance=~\"10.0.0.11:9117\"}\n",
     "legendFormat": "alpha - busy"
    },
    {
     "expr": "apache_workers{state=\"busy\",instance=~\"10.0.0.7:9117\"}",
     "legendFormat": "beta - busy"
    },
    {
     "expr": "apache_workers{state=\"busy\",instance=~\"10.0.0.3:9117\"}",
     "legendFormat": "gamma - busy"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(apache_up{instance=~\"10.0.0.7:9117\"} == 1)",
     "legendFormat": "Beta  Up"
    },
    {
     "expr": "scalar(count(apache_up{instance=~\"10.0.0.3:9117\"} == 0))",
     "legendFormat": "Beta Down"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(apache_up{instance=~\"10.0.0.3:9117\"} == 1)",
     "legendFormat": "Gamma Up"
    },
    {
     "expr": "scalar(count(apache_up{instance=~\"10.0.0.3:9117\"} == 0))",
     "legendFormat": "Gamma Down"
    }
   ]
  },
  {
   "title": "Current total apache accesses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apache_accesses_total{instance=~\"10.0.0.11:9117\"}[1m])",
     "legendFormat": "Alpha"
    },
    {
     "expr": "rate(apache_accesses_total{instance=~\"10.0.0.7:9117\"}[1m])",
     "legendFormat": "Beta"
    },
    {
     "expr": "rate(apache_accesses_total{instance=~\"10.0.0.3:9117\"}[1m])",
     "legendFormat": "Gamma"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_cpuload{instance=~\"10.0.0.11:9117\"}",
     "legendFormat": "Alpha"
    },
    {
     "expr": "apache_cpuload{instance=~\"10.0.0.7:9117\"}",
     "legendFormat": "Beta"
    },
    {
     "expr": "apache_cpuload{instance=~\"10.0.0.3:9117\"}",
     "legendFormat": "Gamma"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"localhost:9100\",job=~\"prometheus\",device=~\"[a-z]*[a-z]\"}[10s])",
     "legendFormat": "balancer"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"10.0.0.11:9100\",job=~\"prometheus\",device=~\"[a-z]*[a-z]\"}[10s])",
     "legendFormat": "alpha"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"10.0.0.7:9100\",job=~\"prometheus\",device=~\"[a-z]*[a-z]\"}[10s])",
     "legendFormat": "beta"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"10.0.0.3:9100\",job=~\"prometheus\",device=~\"[a-z]*[a-z]\"}[10s])",
     "legendFormat": "gamma"
    }
   ]
  }
 ]
}